//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookId { get; set; }
        public string PropName { get; set; }
        public string PropType { get; set; }
        public string PropStatus { get; set; }
        public long PropRent { get; set; }
        public string PropAddress { get; set; }
        public long PropContact { get; set; }
        public string Book { get; set; }
        public string PropDescription { get; set; }
        public string PropSize { get; set; }
        public string PropFacing { get; set; }
        public string PetFriendly { get; set; }
        public string AvailableFor { get; set; }
        public string Flooring { get; set; }
        public string AvailableFrom { get; set; }
        public byte[] HImg1 { get; set; }
        public string CustEmail { get; set; }
        public string SellEmail { get; set; }
        public string SFirstName { get; set; }
        public string SLastName { get; set; }
        public Nullable<long> SMobileNumber { get; set; }
        public byte[] SProfileImage { get; set; }
    }
}
